### ISSUE TITLE
Error on Visual Studio Start

### ISSUE THREAD

**Issue by modulexcite** [ALM-Rangers/Breakpoint-Generator#2] opened 2017-04-27 13:52 UTC
### Installed product versions
- Visual Studio: 2015 Professional
- This extension: 1.1
- OS: Windows 7 SP1 Professional

### Description
After installing the extension, Visual Studio reports a problem (see error below) with the extension every time I start it.

### Steps to recreate
1. Download and install the extension from the [marketplace](https://marketplace.visualstudio.com/items?itemName=VisualStudioALMRangers.BreakpointGenerator)
2. Start Visual Studio 

### Current behavior
Below is the error from Visual Studio Activity Log:
> CreateInstance failed for package [BreakpointGeneratorPackage]Source: 'mscorlib' Description: Could not load file or assembly 'Microsoft.VisualStudio.Shell.14.0, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.Shell.14.0, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. File name: 'Microsoft.VisualStudio.Shell.14.0, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' at System.Reflection.RuntimeAssembly.GetType(RuntimeAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type) at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase) at System.Activator.CreateInstanceFromInternal(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo) at System.AppDomain.CreateInstanceFrom(String assemblyFile, String typeName) WRN: Assembly binding logging is turned OFF. To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1. Note: There is some performance penalty associated with assembly bind failure logging. To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
**80004005 - E_FAIL**

### Expected behavior
It should work.

**Comment by jprg** [comment] 2017-05-01 19:55
Confirmed on Windows 10 Creator's Update.

Workaround: Uninstall/Install

**Comment by modulexcite** [comment] 2017-05-01 21:58
I don't see a new version released on the marketplace, just reinstalling the same version is the workaround?

**Comment by onlyutkarsh** [comment] 2017-05-01 22:44
Hey Guys, We suspect that this issue might be occurring only on machines which have VS 2015 (and no VS2017) installed. Can you please confirm if you have VS 2017 or not?

**Comment by modulexcite** [comment] 2017-05-01 22:52
No I don't have Visual Studio 2017 installed on the machine this was tested on.

**Comment by riaandewet** [comment] 2017-05-02 06:17
Hi. I get the same error. Windows 7 Professional, Visual Studio 2015 Enterprise (No VS2017 installed)

**Comment by lirrik** [comment] 2017-05-08 00:54
Same here. Windows 7 Professional SP1, Visual Studio Professional 2015 Update 3, no Visual Studio 2017 installed. Tried reinstalling extension, same error again.

**Comment by ecoeficiente** [comment] 2017-06-08 14:13
Same here. Windows 10, VS Community 2015, no VS 2017 installed.

**Comment by wpschaub** [comment] 2017-06-09 02:04
Based on initial investigations the extension has a dependency for the VS2017 assemblies to be installed, which is why we're seeing this issue in systems running only VS 2015. What are the core reasons for installing VS2015 and not VS2017?

PavelG offered a temporary work around on the Marketplace. 

Adding this bit of code to **devenv.exe.config** should fix your problem:

```
<dependentAssembly>
    <assemblyIdentity name="Microsoft.VisualStudio.Shell.14.0" publicKeyToken="b03f5f7f11d50a3a" culture="neutral"/>
    <bindingRedirect oldVersion="15.0.0.0" newVersion="14.0.0.0"/>
</dependentAssembly>
```
**IMPORTANT** - This is just an interim workaround!

**Comment by riaandewet** [comment] 2017-06-09 07:22
@wpschaub core reason for "installing VS2015" and not VS2017 is mainly because of employer and current work where the migration to VS2017 have not been finalised, and only VS2015 installed on work computers.

Also [Breakpoint Generator](https://marketplace.visualstudio.com/items?itemName=VisualStudioALMRangers.BreakpointGenerator) states that:

> Some important things to note:
> • The tool only works with Visual Studio 2015 and Visual Studio 2017
> • The tool only works with C# projects

> Works with
> Visual Studio 2015, 2017

otherwise I would not have tried to install it on VS2015.

Will look at the work around in the meantime

**Comment by intnovaction** [comment] 2017-07-15 13:15
It's happening to me with both versions installed and the workaround prevents VS2015 from starting properly :( 
It's a very "dirty" workstation that may need a format & reinstall, so it could be anything

**Comment by onlyutkarsh** [comment] 2018-04-09 22:57
Hello everyone, this issue is fixed now in the latest release. Please [download](https://marketplace.visualstudio.com/items?itemName=VisualStudioALMRangers.BreakpointGenerator) and let us know.

**Closed as completed by onlyutkarsh** 2018-04-09 22:57 UTC
